# Generated by Django 3.2.5 on 2021-07-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointhistory',
            name='point',
            field=models.IntegerField(),
        ),
    ]
