# Generated by Django 3.2.5 on 2021-07-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productefficacy',
            old_name='icon',
            new_name='icon_url',
        ),
    ]
